kind: LocalConfig
apiversion: odo.dev/v1alpha1
ComponentSettings:
  Type: java
  SourceLocation: target/redhat-datagrid-perf-1.0.0-SNAPSHOT-runner.jar
  SourceType: binary
  Ports:
  - 8080/TCP
  - 8443/TCP
  - 8778/TCP
  Application: app
  Project: madou-rhdg
  Name: rhdg-client
  MinMemory: 2Gi
  MaxMemory: 2Gi
  MinCPU: 4000m
  MaxCPU: 4000m
  Url:
  - Name: rhdg-client
    Port: 8080
