{
 "title": "Data Grid - Cache Statistics",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cache_name",
    "label": "Cache Name",
    "query": "metrics(vendor_cache_manager_default_cache_.*_cluster_cache_stats_number_of_entries_in_memory)"
   }
  ]
 },
 "panels": [
  {
   "title": "Objects",
   "type": "singlestat",
   "description": "Total number of distinct object",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg({__name__=~\"vendor_cache_manager_default_cache_($cache_name)_cluster_cache_stats_number_of_entries\"})"
    }
   ]
  },
  {
   "title": "In Memory",
   "type": "singlestat",
   "description": "Total number including replicas",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum({__name__=~\"vendor_cache_manager_default_cache_($cache_name)_statistics_number_of_entries_in_memory\"})"
    }
   ]
  },
  {
   "title": "Evicted",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg({__name__=~\"vendor_cache_manager_default_cache_($cache_name)_cluster_cache_stats_number_of_entries\"}) - sum({__name__=~\"vendor_cache_manager_default_cache_($cache_name)_statistics_number_of_entries_in_memory\"})"
    }
   ]
  },
  {
   "title": "Average READ Time (ns)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg({__name__=~\"vendor_cache_manager_default_cache_($cache_name)_cluster_cache_stats_average_read_time_nanos\"})"
    }
   ]
  },
  {
   "title": "Average WRITE Time (ns)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg({__name__=~\"vendor_cache_manager_default_cache_($cache_name)_cluster_cache_stats_average_write_time_nanos\"})"
    }
   ]
  },
  {
   "title": "Average REMOVE Time (ns)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg({__name__=~\"vendor_cache_manager_default_cache_($cache_name)_cluster_cache_stats_average_remove_time_nanos\"})"
    }
   ]
  },
  { "title": "Advanced", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Objects",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg({__name__=~\"vendor_cache_manager_default_cache_($cache_name)_cluster_cache_stats_number_of_entries\"})",
     "legendFormat": "Objects"
    },
    {
     "expr": "sum({__name__=~\"vendor_cache_manager_default_cache_($cache_name)_statistics_number_of_entries_in_memory\"})",
     "legendFormat": "Objects in memory"
    },
    {
     "expr": "sum({__name__=~\"vendor_cache_manager_default_cache_($cache_name)_cluster_cache_stats_number_of_entries\"}) - sum({__name__=~\"vendor_cache_manager_default_cache_($cache_name)_statistics_number_of_entries_in_memory\"})",
     "legendFormat": "Evicted"
    }
   ]
  },
  {
   "title": "Read/Write",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg({__name__=~\"vendor_cache_manager_default_cache_($cache_name)_cluster_cache_stats_hits\"})+avg({__name__=~\"vendor_cache_manager_default_cache_($cache_name)_cluster_cache_stats_misses\"})",
     "legendFormat": "Read"
    },
    {
     "expr": "avg({__name__=~\"vendor_cache_manager_default_cache_($cache_name)_cluster_cache_stats_stores\"})",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "READ Operations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg({__name__=~\"vendor_cache_manager_default_cache_($cache_name)_cluster_cache_stats_hits\"})",
     "legendFormat": "Hits"
    },
    {
     "expr": "avg({__name__=~\"vendor_cache_manager_default_cache_($cache_name)_cluster_cache_stats_misses\"})",
     "legendFormat": "Misses"
    },
    {
     "expr": "avg({__name__=~\"vendor_cache_manager_default_cache_($cache_name)_cluster_cache_stats_remove_hits\"})",
     "legendFormat": "Remove Hits"
    },
    {
     "expr": "avg({__name__=~\"vendor_cache_manager_default_cache_($cache_name)_cluster_cache_stats_remove_misses\"})",
     "legendFormat": "Remove Misses"
    }
   ]
  }
 ]
}